"""Independent FP64 materialized prefill oracle; generated arrays remain in build/."""
import hashlib
import json
from pathlib import Path
import numpy as np
from generate_decode import bf16, values

ROOT = Path(__file__).resolve().parents[3] / 'build/oracle_data/attention'
CASES = [(r,r,17,0) for r in (1,2,7,8,9,15,16,17,31,32,33,63,64,65)]
CASES += [(r,t,17,0) for r,t in ((2,7),(7,33),(16,256),(17,257),(16,1024),(16,4095),(16,4096))]
CASES += [(7,33,37,kind) for kind in (1,2,3,4)]
CASES += [(33,65,53,0)]
CASES += [(r,r,53,0) for r in (256,1024,4096)]


def oracle(r,t,seed,kind):
    q = values(t*896,seed,kind,0).reshape(t,14,64)[t-r:]
    k = values(t*128,seed+3,kind,1).reshape(t,2,64)
    v = values(t*128,seed+7,kind,2).reshape(t,2,64)
    if kind == 4:
        # Uniform, finite scaled scores below -1e30 expose finite sentinels.
        q[:] = bf16(1e16)
        k[:] = bf16(-1e16)
    eager,online = np.empty((r,14,64),np.float32),np.empty((r,14,64),np.float32)
    # Chunk query rows to bound oracle scratch; never stream an online recurrence.
    for h in range(14):
        for start in range(0,r,16):
            stop = min(start+16,r)
            scores = bf16(q[start:stop,h] @ k[:,h//7].T / 8).astype(np.float64)
            future = np.arange(t)[None,:] > (t-r+np.arange(start,stop))[:,None]
            scores[future] = -np.inf
            p = np.exp(scores-scores.max(axis=1,keepdims=True))
            p /= p.sum(axis=1,keepdims=True)
            eager[start:stop,h] = bf16(bf16(p).astype(np.float64) @ v[:,h//7])
            online[start:stop,h] = bf16(p @ v[:,h//7])
    return eager.reshape(-1),online.reshape(-1)


def main():
    ROOT.mkdir(parents=True,exist_ok=True)
    lines=['"""Generated by generate_prefill.py; see prefill_manifest.json."""',f'comptime PREFILL_CASE_COUNT = {len(CASES)}']
    for pos,label in enumerate(('query_rows','key_rows','seed','kind')):
        lines += [f'def prefill_case_{label}(case_id: Int) -> Int:']
        for i,spec in enumerate(CASES):
            lines += [f'    if case_id == {i}:',f'        return {spec[pos]}']
        lines += ['    return -1','']
    hashes={}
    for i,spec in enumerate(CASES):
        eager,online=oracle(*spec)
        data_path=ROOT/f'prefill_{i}.npy'
        np.save(data_path,np.stack((eager,online)),allow_pickle=False)
        hashes[data_path.name]=hashlib.sha256(data_path.read_bytes()).hexdigest()
    lines += ['from std.python import Python',
              'def prefill_case_expected(case_id: Int, online: Bool = False) raises -> List[Float32]:',
              '    var np = Python.import_module("numpy")',
              '    var arrays = np.load("build/oracle_data/attention/prefill_"+String(case_id)+".npy", allow_pickle=False)',
              '    var array = arrays[1 if online else 0]',
              '    var result = List[Float32]()',
              '    for i in range(Int(py=array.size)):',
              '        result.append(Float32(py=array[i]))',
              '    return result^', '']
    path=ROOT/'prefill_data.mojo'
    path.write_text('\n'.join(lines))
    record=dict(oracle='NumPy CPU FP64 materialized QK/softmax/PV; BF16 scores/output; eager BF16 probabilities and FP64 probabilities',numpy=np.__version__,cases=CASES,array_sha256=hashes,atol=.015625,rtol=.015625,query_positions='T-R through T-1',generator_sha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),data_sha256=hashlib.sha256(path.read_bytes()).hexdigest())
    (ROOT/'prefill_manifest.json').write_text(json.dumps(record,indent=2)+'\n')
    print(len(CASES),'independent prefill oracle cases generated')

if __name__=='__main__':
    main()
