"""Generate bounded decode outputs with the locked NumPy FP64 CPU oracle.

Run: uv run --locked python tests/fixtures/attention/generate_decode.py
No model weights or network access. Independent materialized dot/softmax/PV,
with BF16 score rounding, and with/without the baseline BF16 probability round.
"""

import hashlib
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[3] / "build/oracle_data/attention"
ROOT.mkdir(parents=True, exist_ok=True)
CASES = [
    (t, 17, 0)
    for t in (1, 7, 16, 31, 32, 33, 63, 64, 65, 255, 256, 257, 1024, 4095, 4096)
]
CASES += [(t, 37, kind) for kind in (1, 2, 3) for t in (7, 257, 4096)]


def bf16(x):
    bits = np.asarray(x, dtype=np.float32).view(np.uint32)
    return ((bits + 0x7FFF + ((bits >> 16) & 1)) & 0xFFFF0000).view(np.float32)


def values(n, seed, kind, operand):
    i = np.arange(n, dtype=np.int64)
    x = (((i * 37 + seed * 19 + (i // 17) * 11) % 257) - 128) / 64.0
    if kind == 1 and operand < 2:
        x *= 8
    if kind == 2 and operand < 2:
        x[:] = 8
    if kind == 3 and operand == 2:
        x = np.where((i // 128) % 2 == 0, 1, -1) * (1 + (i % 7) / 64.0)
    return bf16(x).astype(np.float64)


def oracle(t, seed, kind):
    q = values(896, seed, kind, 0).reshape(14, 64)
    k = values(t * 128, seed + 3, kind, 1).reshape(t, 2, 64)
    v = values(t * 128, seed + 7, kind, 2).reshape(t, 2, 64)
    # Materialize the score matrix independently from the streaming kernel.
    s = bf16(np.einsum("hd,thd->ht", q, np.repeat(k, 7, axis=1)) / 8).astype(
        np.float64
    )
    p = np.exp(s - s.max(axis=1, keepdims=True))
    p /= p.sum(axis=1, keepdims=True)
    eager = bf16(
        np.einsum(
            "ht,thd->hd", bf16(p).astype(np.float64), np.repeat(v, 7, axis=1)
        )
    )
    online = bf16(np.einsum("ht,thd->hd", p, np.repeat(v, 7, axis=1)))
    return eager.reshape(-1), online.reshape(-1)


def main():
    lines = [
        '"""Generated by generate_decode.py; see decode_manifest.json."""',
        "",
    ]
    lines += [f"comptime DECODE_CASE_COUNT = {len(CASES)}", ""]
    for pos, label in enumerate(("rows", "seed", "kind")):
        lines += [f"def decode_case_{label}(case_id: Int) -> Int:"]
        for i, spec in enumerate(CASES):
            lines += [f"    if case_id == {i}:", f"        return {spec[pos]}"]
        lines += ["    return -1", ""]
    lines += [
        "def decode_case_expected(case_id: Int, diagnostic: Bool = False) -> List[Float32]:"
    ]
    for i, spec in enumerate(CASES):
        eager, online = oracle(*spec)
        lines += [f"    if case_id == {i}:"]
        for prefix, array in [
            ("        if diagnostic:", online),
            ("        else:", eager),
        ]:
            lines += [prefix, "            return ["]
            for start in range(0, len(array), 8):
                lines += [
                    "                "
                    + ", ".join(str(float(x)) for x in array[start : start + 8])
                    + ","
                ]
            lines += ["            ]"]
    lines += ["    return []", ""]
    path = ROOT / "decode_data.mojo"
    path.write_text("\n".join(lines))
    manifest = {
        "oracle": "NumPy CPU FP64 materialized attention; round scaled QK to BF16; paired eager BF16 probabilities and FP64 probabilities; output BF16",
        "numpy": np.__version__,
        "atol": 0.015625,
        "rtol": 0.015625,
        "cases": CASES,
        "inputs": "decode_input deterministic integer recipe; contiguous Q[1,14,64], KV[T,2,64]",
        "generator_sha256": hashlib.sha256(
            Path(__file__).read_bytes()
        ).hexdigest(),
        "data_sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
    }
    (ROOT / "decode_manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n"
    )


if __name__ == "__main__":
    main()
